### PR TITLE
Changing hypothesis version to 4.8.0

### PR DESCRIPTION
**Pull request by AaronCritchley**

### CODE REVIEW

**Comment by dwillmer** [comment]
My hunch is that changing the `pip install numpy` to `conda install numpy` might work...

**Comment by dwillmer** [comment]
Might as well go all out and upgrade to `4.7.9` like dependabot says as well...

**Comment by AaronCritchley** [comment]
Done!

**Comment by dwillmer** [comment]
😺

**Comment by AaronCritchley** [comment]
Can't figure out how to cancel the appveyor job from their UI which likely means my change will block for at least an hour (hopefully it wont do it for every setup on the list), sorry! 😓 

EDIT: From looking at forums it looks like a perms things, which is annoying!

**Comment by dwillmer** [comment]
No worries at all, will merge in the morning assuming it passes

**Comment by dwillmer** [comment]
Thanks!

**Comment by dwillmer** [comment]
These appveyor diffs are due to the formatting changes in numpy 1.14, which all the unit-tests have been updated for. I'd recommend setting a minimum of `numpy>=1.14` in the requirements.txt and that should get them all passing.

Seems very silly that it's picking up numpy 1.13.1 at the moment.

**Comment by dwillmer** [comment]
Nice work @AaronCritchley , looked like Appveyor was being quite annoying!

**Comment by dwillmer** [comment]
Consistently ~20 seconds faster with the new hypothesis, which is ~30% of the test runtime. Nice find! :)

**Pull request merged**
