### PR TITLE
Parallel versions of scaling functions

### PR DESCRIPTION
**Pull request by rjenc29**
Parallel (CPU) versions of scaling functions, using numba.prange

### CODE REVIEW

**Comment by dwillmer** [comment]
Awesome stuff, looks good to me.

What's the criteria for the speedups? roughly >1e6 elements per column?

**Comment by rjenc29** [comment]
Fewer than that, actually - I will add a notebook at the weekend to illustrate

**Comment by pawroman** [comment]
It would be nice to get some pre-tuned heuristics for automatically picking sequential vs parallel for this

**Review by dwillmer — APPROVED** [review]
LGTM, nice work!

**Comment by rjenc29** [comment]
oh, so close

**Comment by rjenc29** [comment]
well, I think the offending line is hit (multiple times) by the committed tests, hmm

**Comment by dwillmer** [comment]
Yea, looks good to me, am happy to ignore the codecov/patch given that the codecov/project metric has gone up!

**Comment by dwillmer** [comment]
Very nice, merged! Thanks!

**Comment by rjenc29** [comment]
Nice one, ta!

**Pull request merged**
