### PR TITLE
LU - compact method

### PR DESCRIPTION
**Pull request by rjenc29**
New Feature
This is just thought really - a different LU factorisation.  
Interested in your thoughts and suggestions for benchmarks / tests / whether it's got legs and so on.  

- [x] Code conforms to style guide
- [ ] Doctests
- [x] Unit-tests
- [ ] Documentation
- [ ] New line item in [releases.md](releases.md)
- [ ] Info added to `literature` directory

Bug Report

- [ ] Minimal repro in a test function

### CODE REVIEW

**Comment by dwillmer** [comment]
LGTM, that's quite a speedup!

**Comment by dwillmer** [comment]
Approved... @rjenc29 did you want to merge this for the first release?

**Comment by rjenc29** [comment]
Yep, that would be fine with me.  I have a couple of other LU methods in the works (not ready yet).  

I appreciate 'lu_compact' isn't a great name - will think of something better in due course perhaps.

**Comment by pawroman** [comment]
LGTM, merging

**Pull request merged**
