### PR TITLE
Codacy fixes

### PR DESCRIPTION
**Pull request by dwillmer**
Just a few fixes from the codacy reviews.

### CODE REVIEW

**Comment by dwillmer** [comment]
@rjenc29 - Now you're a maintainer on the org it's time for me to stop merging my own PRs...

Could you review please and merge if happy?

**Comment by rjenc29** [comment]
These changes all look good to me; I take it the __all__ functions should be referenced by name going forwards

**Comment by rjenc29** [comment]
...so we define a scope of public importable fns by fn name

**Comment by dwillmer** [comment]
Yea, precisely - the AST is quite different between `np.abs(x)` and `abs(x)`. The current idea is to only treat the latter as transformable, and treat the `module.func` format as a sign that the author specifically wants to use that function without transformations.

There's some brief notes in lines 38-48 in `core/ast_transforms/transformer.py`, but i haven't written up the docs for the AST transforms yet as i'm still playing around with a few edge cases.

**Pull request merged**
