### PR TITLE
LU Decomposition

### PR DESCRIPTION
**Pull request by dwillmer**

### CODE REVIEW

**Review by rjenc29 — COMMENTED** [review]
Looks  great.  Maybe assert that A is square?  I like the tests - I wonder if testing nopython/nogil compiled versions alongside plain Python is something we could use more widely.

**Comment by rjenc29** [comment]
By extension, maybe assert that L, U and A are the same shape and that L and U have been initialised per expectation (zeros).

**Comment by rjenc29** [comment]
The pdfs are very handy

**Comment by rjenc29** [comment]
I guess the question I never asked: why not internalise the creation of L and U and then return them from the function as a pair of outputs?

**Comment by rjenc29** [comment]
i.e. 

    L = np.zeros_like(A, dtype=np.float64)
    U = np.zeros_like(A, dtype=np.float64)
    ...
    return L, U

**Comment by dwillmer** [comment]
Yea, will add in the shape assertions, nice one!

**Comment by dwillmer** [comment]
For the memory allocation, it's done mainly for performance (this is 1us vs scipy 20us for a small matrix), and calling it in a loop will actually materialise that gain. The main use case for this in fastats is probably going to be iterating over a high-dimensional matrix and using `L, U` to solve the equations. Only allocating the arrays once saves ~10-20% of runtime.

Having said that, I do agree with you though, perhaps we should add a wrapper function to give the option:

```python
def lu(A):
    L, U = np.zeros_like(A), np.zeros_like(A)
    lu_inplace(A, L, U)
    return L, U
```

**Comment by dwillmer** [comment]
@rjenc29 - the latest commit adds the API you asked for - `L, U = lu(A)`, which just wraps the old function (which has been renamed to `lu_inplace`).

**Comment by rjenc29** [comment]
That's just the ticket, nice one

**Pull request merged**
