### PR TITLE
Add relu and softplus functions

### PR DESCRIPTION
**Pull request by pawroman**
These two are fairly popular as neural network activation functions.

### CODE REVIEW

**Comment by pawroman** [comment]
The Windows build failed... Well there always must be some kind of problem with this OS. 🤕

**Comment by dwillmer** [comment]
Awesome stuff, thanks @pawroman!

The code is really neat - the only comment i have is whether `rectify.py` is the right module name - ReLU is a rectifier, but ReLU and softplus are generally classified as `activation` functions rather than rectifiers.

Perhaps `activations.py` (or similar) is a better module name? Or maybe separate `relu` and `softplus` modules?

**Comment by dwillmer** [comment]
and yea... the Windows builds are a pain! i've switched off AppVeyor until I have more time to work on #14 :)

**Comment by pawroman** [comment]
Renamed - I think keeping them together makes sense.

**Comment by dwillmer** [comment]
Awesome stuff, thanks @pawroman - merged!

**Pull request merged**
