### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by dwillmer**
Updating version number for first prod release

### CODE REVIEW

**Comment by dwillmer** [comment]
Am pulling the trigger on a release, we can update the files later once the unrelated upstream build issues are fixed.

**Comment by dwillmer** [comment]
To summarise current state:
- numba >= 0.41 on linux is failing due to internal lowering errors (unsure if it's been reported, will check tomorrow).
- numba == 0.40 on windows is failing due to segfaults on 64-bit versions.

**Comment by dwillmer** [comment]
- numba == 0.39 is also failing on 64-bit windows with segfaults

**Comment by dwillmer** [comment]
Ok, in summary:

- Added python 3.7 to appveyor config (32- and 64-bit)
- Added python 3.7 and 3.7-dev to travis-ci config
- Changed travis-ci config to use Xenial instead of default Trusty to get 3.7 support
- Removed pre-release warning from readme.md and changed setup.py to be `Status 5 - Prod`
- Changed numba constraint to be 0.41 and above - lower versions segfault on windows
- Changed `if`-statement with `ValueError` into direct assertion to bypass number lowering error

@fastats/core - I've had to change the allowed numba versions, and we're now supporting/testing 3.7 properly, so am upgrading this PR to be a `2019.1` release. Please review and merge if you're happy with the changes above.

Specifically - @rjenc29 are you happy with the scaling change from `ValueError` to `AssertionError`?

Thanks!

**Comment by rjenc29** [comment]
@dwillmer yeah, that change looks sensible & thanks for sorting it out!

**Review by rjenc29 — APPROVED** [review]
These changes all look sensible to me; good to go!

**Comment by dwillmer** [comment]
Nice one, thanks - feel free to merge and i'll kick off some package builds for pyPI

**Comment by rjenc29** [comment]
Fantastic!

**Pull request merged**
