### PR TITLE
PCA implementation (returning transformed data) + unit-tests

### PR DESCRIPTION
**Pull request by dwillmer**

### CODE REVIEW

**Comment by dwillmer** [comment]
@pawroman @rjenc29 @fastats/core - please review!

This is a simplistic PCA implementation which just returns the dimensionally-reduced data, without eigenvectors or eigenvalues (given the current limitations of numba return values).

The numbers are good compared with sklearn, and is a good starting point for building out a proper linear algebra PCA framework.

**Comment by rjenc29** [comment]
Hey, looks good.  I think eigh returns values/vectors in a guaranteed sort order (unlike eig)

**Comment by dwillmer** [comment]
Good spot, unfortunately it returns them in ascending order though, so we still need to perform 
a reverse.

Have made the change - may be worth writing a custom version of eigh to avoid this.

**Comment by dwillmer** [comment]
Thanks! ready for review.

**Review by rjenc29 — APPROVED** [review]
Looks good to me, shall I go ahead and merge?

**Comment by dwillmer** [comment]
Yes please, if you think it's ready.

**Pull request merged**
