### PR TITLE
Implementing EWMA

### PR DESCRIPTION
**Pull request by AaronCritchley**
Just a WIP for now, as had a few questions for @fastats/core - will mark when ready for real review.

New Feature

- [x] Code conforms to style guide
- [x] Doctests
- [x] Unit-tests
- [ ] Documentation
- [x] New line item in [releases.md](https://github.com/fastats/fastats/blob/master/releases.md)
- [ ] Info added to `literature` directory

Still to-do:

- [x] Add benchmarks
- [x] more comprehensive testing
- [x] Add to __init__ for maths

### CODE REVIEW

**Comment by AaronCritchley** [comment]
Some questions for @rjenc29 / @pawroman / @dwillmer:

* What methods of decay would we like to support for ewm functions, fwiw, Pandas supports alpha / span / centre of mass / halflife - would we like to support all or just a subset?
* Would we like rolling and non-rolling ewm functions to be implemented separately, or all together?
* Would we prefer a 'pandas-like' interface to ewm funcs? or just standalone functions?
* Any odd edge-cases you'd like in the tests?

**Comment by dwillmer** [comment]
Looks good, nice one... what's the performance difference like using numba over pandas?

- i'm pretty sure @rjenc29 has written a function which converts the various pandas decay parameters into a single one, which simplifies the hot inner loop.

- for rolling vs rolling - that depends on the attribute being applied, eg mean and std have fast streaming versions, but not all do - the ewm code should be largely the same for all of them.

- definitely just standalone functions - the OO interface to these things gets unwieldy very quickly. fastats can pass functions to jitted code, so we'll use that instead of inheritance for code reuse.

- for edge cases, the issues we've seen with pandas ewm tend to be around nan handling, especially where the nan values make up the entire window. bottleneck used to change the behaviour here as well, so various pandas installs have given different answers. i'd focus on getting the correct behaviour for all possibilities of nan inputs - happy to help if you want it.

Thanks!

**Comment by AaronCritchley** [comment]
Added benchmarks in `_notebooks/ewma_benchmarking`, for reference:

shape | pandas time (s) | fastats time (s) | time_diff_multiple
-- | -- | -- | --
(10, 100) | 0.001445 | 0.000004 | 410.0
(10, 1000) | 0.007467 | 0.000011 | 677.0
(10, 10000) | 0.067716 | 0.000095 | 710.0
(10, 100000) | 0.673922 | 0.003158 | 213.0
(10, 1000000) | 6.861648 | 0.038730 | 177.0
(100, 100) | 0.001680 | 0.000031 | 54.0
(1000, 1000) | 0.073510 | 0.002116 | 35.0
(10000, 10000) | 9.222459 | 0.386896 | 24.0
(100, 10) | 0.000802 | 0.000017 | 46.0
(1000, 10) | 0.001307 | 0.000166 | 8.0
(10000, 10) | 0.006794 | 0.001618 | 4.0
(100000, 10) | 0.061514 | 0.016315 | 4.0
(1000000, 10) | 0.658155 | 0.167085 | 4.0

Will finish off the rest of the TODO's over the weekend!

**Comment by rjenc29** [comment]
Looks great! 

I think there's a valid argument to have a 'finite values only' implementation, and tackle a nan/inf aware version separately, personally (with suitable advertising of the intended usage).

Might be worth adding a sensibility check for the half-life value.  Logically, it should be a finite number greater than zero, in my opinion.  Naturally, Pandas allows np.nan etc etc :)

**Comment by AaronCritchley** [comment]
All good with me, I'll add the suggested check for halflife (and test), keep the xfail test for nan's and clear up the documentation that it's only expected to work with finite values.

Merging in develop should fix the build, will address over the next few days.

I'll look into some other ewm functions over the next few days, will raise separate PR's accordingly.

**Comment by AaronCritchley** [comment]
Done, and updated benchmarking notebook - comment above is updated if you want to get a quick overview of perf.

**Comment by rjenc29** [comment]
Excellent stuff; this is an exceptional speedup over Pandas.

**Pull request merged**
